import { Logger, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ISeeder } from '../../seed.interface';
import { Equipment } from 'src/domains/equipment/equipment/entities/equipment.entity';
import { EquipmentType } from 'src/domains/equipment/equipment-type/entities/equipment-type.entity';

@Injectable()
export class EquipmentSeed implements ISeeder {
    private readonly logger = new Logger(EquipmentSeed.name)
    constructor(
    @InjectRepository(Equipment)
    private readonly equipmentRepository: Repository<Equipment>,
    @InjectRepository(EquipmentType)
    private readonly equipmentTypeRepository: Repository<EquipmentType>,
  ) {}

  async setupInitialData(insertDebugData : boolean): Promise<void> {
    const cnt = await this.equipmentRepository.count();
    if (cnt === 0 ){
      await this.insertDefaultData();
      if(insertDebugData) {
        await this.insertTestData();
      }
    }
  }


  async insertDefaultData(): Promise<void> {
    this.logger.log('No equipment found, inserting default data...');

    let equipmentTypeList = await this.equipmentTypeRepository.find({ where: {valid_record: true} });
    if (!equipmentTypeList) {
        this.logger.log('No foreign key exists for the equipment');
        return;
    }

    const equipmentDefaultList = [
      { id : 1, name : 'G211', spec: '', code: 'G01_1', equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 2}},
      { id : 2, name : 'G212', spec: '', code: 'G01_2',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 2}},
      { id : 3, name : 'G221', spec: '', code: 'G02_1',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 3}},
      { id : 4, name : 'G222', spec: '', code: 'G02_2',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 3}},
      { id : 5, name : 'G111', spec: '', code: 'G05_1',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 4}},
      { id : 6, name : 'G112', spec: '', code: 'G05_2',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 4}},
      { id : 7, name : 'G121', spec: '', code: 'G06_1',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 5}},
      { id : 8, name : 'G122', spec: '', code: 'G06_2',equipment_type: {id : equipmentTypeList[3].id}, warehouse: {id : 5}},

      { id : 9, name :  'STACKER_CRANE1', spec: '', code: 'SC1', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 10, name : 'STACKER_CRANE2', spec: '', code: 'SC2', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 11, name : 'STACKER_CRANE3', spec: '', code: 'SC3', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 12, name : 'STACKER_CRANE4', spec: '', code: 'SC4', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 13, name : 'STACKER_CRANE5', spec: '', code: 'SC5', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 14, name : 'STACKER_CRANE6', spec: '', code: 'SC6', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 15, name : 'STACKER_CRANE7', spec: '', code: 'SC7', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 16, name : 'STACKER_CRANE8', spec: '', code: 'SC8', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 17, name : 'STACKER_CRANE9', spec: '', code: 'SC9', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      { id : 18, name : 'STACKER_CRANE10', spec: '', code: 'SC10', equipment_type: {id : equipmentTypeList[2].id}, warehouse: {id : 1}},
      
      { id : 28, name : 'CNV_1110', spec: '', code: 'CNV_1110', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 29, name : 'CNV_1111', spec: '', code: 'CNV_1111', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 30, name : 'CNV_1112', spec: '', code: 'CNV_1112', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 31, name : 'CNV_1120', spec: '', code: 'CNV_1120', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 32, name : 'CNV_1121', spec: '', code: 'CNV_1121', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 33, name : 'CNV_1125', spec: '', code: 'CNV_1125', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 34, name : 'CNV_1126', spec: '', code: 'CNV_1126', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 35, name : 'CNV_1127', spec: '', code: 'CNV_1127', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 36, name : 'CNV_1130', spec: '', code: 'CNV_1130', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 37, name : 'CNV_1131', spec: '', code: 'CNV_1131', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 38, name : 'CNV_1135', spec: '', code: 'CNV_1135', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 39, name : 'CNV_1136', spec: '', code: 'CNV_1136', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 40, name : 'CNV_1137', spec: '', code: 'CNV_1137', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 41, name : 'CNV_1140', spec: '', code: 'CNV_1140', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 42, name : 'CNV_1141', spec: '', code: 'CNV_1141', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 43, name : 'CNV_1145', spec: '', code: 'CNV_1145', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 44, name : 'CNV_1146', spec: '', code: 'CNV_1146', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 45, name : 'CNV_1147', spec: '', code: 'CNV_1147', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 46, name : 'CNV_1150', spec: '', code: 'CNV_1150', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 47, name : 'CNV_1151', spec: '', code: 'CNV_1151', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 48, name : 'CNV_1155', spec: '', code: 'CNV_1155', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 49, name : 'CNV_1156', spec: '', code: 'CNV_1156', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 50, name : 'CNV_1157', spec: '', code: 'CNV_1157', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 51, name : 'CNV_1160', spec: '', code: 'CNV_1160', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 52, name : 'CNV_1161', spec: '', code: 'CNV_1161', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 53, name : 'CNV_1165', spec: '', code: 'CNV_1165', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 54, name : 'CNV_1166', spec: '', code: 'CNV_1166', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 55, name : 'CNV_1167', spec: '', code: 'CNV_1167', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 56, name : 'CNV_1170', spec: '', code: 'CNV_1170', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 57, name : 'CNV_1171', spec: '', code: 'CNV_1171', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 58, name : 'CNV_1175', spec: '', code: 'CNV_1175', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 59, name : 'CNV_1176', spec: '', code: 'CNV_1176', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 60, name : 'CNV_1177', spec: '', code: 'CNV_1177', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 61, name : 'CNV_1180', spec: '', code: 'CNV_1180', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 62, name : 'CNV_1181', spec: '', code: 'CNV_1181', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 63, name : 'CNV_1185', spec: '', code: 'CNV_1185', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 64, name : 'CNV_1186', spec: '', code: 'CNV_1186', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 65, name : 'CNV_1187', spec: '', code: 'CNV_1187', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 66, name : 'CNV_1190', spec: '', code: 'CNV_1190', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 67, name : 'CNV_1191', spec: '', code: 'CNV_1191', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 68, name : 'CNV_1195', spec: '', code: 'CNV_1195', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 69, name : 'CNV_1196', spec: '', code: 'CNV_1196', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 70, name : 'CNV_1197', spec: '', code: 'CNV_1197', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 71, name : 'CNV_1200', spec: '', code: 'CNV_1200', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 72, name : 'CNV_1201', spec: '', code: 'CNV_1201', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 73, name : 'CNV_1202', spec: '', code: 'CNV_1202', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 74, name : 'CNV_1310', spec: '', code: 'CNV_1310', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 75, name : 'CNV_1311', spec: '', code: 'CNV_1311', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 76, name : 'CNV_1312', spec: '', code: 'CNV_1312', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 77, name : 'CNV_1313', spec: '', code: 'CNV_1313', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 78, name : 'CNV_1314', spec: '', code: 'CNV_1314', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 79, name : 'CNV_1315', spec: '', code: 'CNV_1315', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 80, name : 'CNV_1316', spec: '', code: 'CNV_1316', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 81, name : 'CNV_1317', spec: '', code: 'CNV_1317', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 82, name : 'CNV_1318', spec: '', code: 'CNV_1318', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 83, name : 'CNV_1320', spec: '', code: 'CNV_1320', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 84, name : 'CNV_1321', spec: '', code: 'CNV_1321', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 85, name : 'CNV_1322', spec: '', code: 'CNV_1322', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 86, name : 'CNV_1323', spec: '', code: 'CNV_1323', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 87, name : 'CNV_1324', spec: '', code: 'CNV_1324', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 88, name : 'CNV_1325', spec: '', code: 'CNV_1325', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 89, name : 'CNV_1326', spec: '', code: 'CNV_1326', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 90, name : 'CNV_1327', spec: '', code: 'CNV_1327', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 91, name : 'CNV_1328', spec: '', code: 'CNV_1328', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 92, name : 'CNV_1330', spec: '', code: 'CNV_1330', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 93, name : 'CNV_1331', spec: '', code: 'CNV_1331', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 94, name : 'CNV_1332', spec: '', code: 'CNV_1332', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 95, name : 'CNV_1333', spec: '', code: 'CNV_1333', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 96, name : 'CNV_1334', spec: '', code: 'CNV_1334', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 97, name : 'CNV_1335', spec: '', code: 'CNV_1335', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 98, name : 'CNV_1336', spec: '', code: 'CNV_1336', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 99, name : 'CNV_1337', spec: '', code: 'CNV_1337', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 100, name : 'CNV_1338', spec: '', code: 'CNV_1338', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 101, name : 'CNV_1340', spec: '', code: 'CNV_1340', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 102, name : 'CNV_1341', spec: '', code: 'CNV_1341', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 103, name : 'CNV_1342', spec: '', code: 'CNV_1342', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 104, name : 'CNV_1343', spec: '', code: 'CNV_1343', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 105, name : 'CNV_1344', spec: '', code: 'CNV_1344', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 106, name : 'CNV_1345', spec: '', code: 'CNV_1345', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 107, name : 'CNV_1346', spec: '', code: 'CNV_1346', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 108, name : 'CNV_1347', spec: '', code: 'CNV_1347', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 109, name : 'CNV_1348', spec: '', code: 'CNV_1348', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 110, name : 'CNV_1350', spec: '', code: 'CNV_1350', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 111, name : 'CNV_1351', spec: '', code: 'CNV_1351', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 112, name : 'CNV_1352', spec: '', code: 'CNV_1352', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 113, name : 'CNV_1353', spec: '', code: 'CNV_1353', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 114, name : 'CNV_1354', spec: '', code: 'CNV_1354', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 115, name : 'CNV_1355', spec: '', code: 'CNV_1355', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 116, name : 'CNV_1356', spec: '', code: 'CNV_1356', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 117, name : 'CNV_1357', spec: '', code: 'CNV_1357', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 118, name : 'CNV_1358', spec: '', code: 'CNV_1358', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 119, name : 'CNV_1360', spec: '', code: 'CNV_1360', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 120, name : 'CNV_1361', spec: '', code: 'CNV_1361', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 121, name : 'CNV_1362', spec: '', code: 'CNV_1362', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 122, name : 'CNV_1363', spec: '', code: 'CNV_1363', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 123, name : 'CNV_1364', spec: '', code: 'CNV_1364', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 124, name : 'CNV_1365', spec: '', code: 'CNV_1365', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 125, name : 'CNV_1366', spec: '', code: 'CNV_1366', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 126, name : 'CNV_1367', spec: '', code: 'CNV_1367', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 127, name : 'CNV_1368', spec: '', code: 'CNV_1368', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 128, name : 'CNV_1370', spec: '', code: 'CNV_1370', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 129, name : 'CNV_1371', spec: '', code: 'CNV_1371', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 130, name : 'CNV_1372', spec: '', code: 'CNV_1372', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 131, name : 'CNV_1373', spec: '', code: 'CNV_1373', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 132, name : 'CNV_1374', spec: '', code: 'CNV_1374', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 133, name : 'CNV_1380', spec: '', code: 'CNV_1380', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 134, name : 'CNV_1381', spec: '', code: 'CNV_1381', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 135, name : 'CNV_1382', spec: '', code: 'CNV_1382', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 136, name : 'CNV_1383', spec: '', code: 'CNV_1383', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 137, name : 'CNV_1384', spec: '', code: 'CNV_1384', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 138, name : 'CNV_1385', spec: '', code: 'CNV_1385', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 139, name : 'CNV_1386', spec: '', code: 'CNV_1386', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 140, name : 'CNV_1387', spec: '', code: 'CNV_1387', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 141, name : 'CNV_1390', spec: '', code: 'CNV_1390', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 142, name : 'CNV_1391', spec: '', code: 'CNV_1391', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 143, name : 'CNV_1392', spec: '', code: 'CNV_1392', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 144, name : 'CNV_1393', spec: '', code: 'CNV_1393', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 145, name : 'CNV_1394', spec: '', code: 'CNV_1394', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 146, name : 'CNV_1395', spec: '', code: 'CNV_1395', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 147, name : 'CNV_1396', spec: '', code: 'CNV_1396', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 148, name : 'CNV_1397', spec: '', code: 'CNV_1397', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 149, name : 'CNV_1410', spec: '', code: 'CNV_1410', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 150, name : 'CNV_1411', spec: '', code: 'CNV_1411', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 151, name : 'CNV_1412', spec: '', code: 'CNV_1412', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 152, name : 'CNV_1413', spec: '', code: 'CNV_1413', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 153, name : 'CNV_1415', spec: '', code: 'CNV_1415', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 154, name : 'CNV_1418', spec: '', code: 'CNV_1418', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 155, name : 'CNV_1419', spec: '', code: 'CNV_1419', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 156, name : 'CNV_1420', spec: '', code: 'CNV_1420', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 157, name : 'CNV_1421', spec: '', code: 'CNV_1421', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 158, name : 'CNV_1422', spec: '', code: 'CNV_1422', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 159, name : 'CNV_1425', spec: '', code: 'CNV_1425', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 160, name : 'CNV_1426', spec: '', code: 'CNV_1426', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 161, name : 'CNV_1428', spec: '', code: 'CNV_1428', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 162, name : 'CNV_1429', spec: '', code: 'CNV_1429', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 163, name : 'CNV_1430', spec: '', code: 'CNV_1430', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 164, name : 'CNV_1431', spec: '', code: 'CNV_1431', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 165, name : 'CNV_1432', spec: '', code: 'CNV_1432', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 166, name : 'CNV_1435', spec: '', code: 'CNV_1435', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 167, name : 'CNV_1438', spec: '', code: 'CNV_1438', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 168, name : 'CNV_1439', spec: '', code: 'CNV_1439', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 169, name : 'CNV_1440', spec: '', code: 'CNV_1440', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 170, name : 'CNV_1441', spec: '', code: 'CNV_1441', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 171, name : 'CNV_1442', spec: '', code: 'CNV_1442', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 172, name : 'CNV_1445', spec: '', code: 'CNV_1445', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 173, name : 'CNV_1448', spec: '', code: 'CNV_1448', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 174, name : 'CNV_1449', spec: '', code: 'CNV_1449', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 175, name : 'CNV_1450', spec: '', code: 'CNV_1450', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 176, name : 'CNV_1451', spec: '', code: 'CNV_1451', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 177, name : 'CNV_1452', spec: '', code: 'CNV_1452', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 178, name : 'CNV_1455', spec: '', code: 'CNV_1455', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 179, name : 'CNV_1458', spec: '', code: 'CNV_1458', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 180, name : 'CNV_1459', spec: '', code: 'CNV_1459', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 181, name : 'CNV_1460', spec: '', code: 'CNV_1460', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 182, name : 'CNV_1461', spec: '', code: 'CNV_1461', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 183, name : 'CNV_1462', spec: '', code: 'CNV_1462', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 184, name : 'CNV_1465', spec: '', code: 'CNV_1465', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 185, name : 'CNV_1468', spec: '', code: 'CNV_1468', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 186, name : 'CNV_1469', spec: '', code: 'CNV_1469', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 187, name : 'CNV_1470', spec: '', code: 'CNV_1470', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 188, name : 'CNV_1471', spec: '', code: 'CNV_1471', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 189, name : 'CNV_1472', spec: '', code: 'CNV_1472', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 190, name : 'CNV_1475', spec: '', code: 'CNV_1475', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 191, name : 'CNV_1478', spec: '', code: 'CNV_1478', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 192, name : 'CNV_1479', spec: '', code: 'CNV_1479', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 193, name : 'CNV_1480', spec: '', code: 'CNV_1480', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 194, name : 'CNV_1481', spec: '', code: 'CNV_1481', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 195, name : 'CNV_1482', spec: '', code: 'CNV_1482', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 196, name : 'CNV_1485', spec: '', code: 'CNV_1485', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 197, name : 'CNV_1488', spec: '', code: 'CNV_1488', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 198, name : 'CNV_1489', spec: '', code: 'CNV_1489', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 199, name : 'CNV_1490', spec: '', code: 'CNV_1490', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 200, name : 'CNV_1491', spec: '', code: 'CNV_1491', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 201, name : 'CNV_1492', spec: '', code: 'CNV_1492', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 202, name : 'CNV_1493', spec: '', code: 'CNV_1493', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 203, name : 'CNV_1495', spec: '', code: 'CNV_1495', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 204, name : 'CNV_1498', spec: '', code: 'CNV_1498', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 205, name : 'CNV_1499', spec: '', code: 'CNV_1499', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 206, name : 'CNV_1510', spec: '', code: 'CNV_1510', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 207, name : 'CNV_1511', spec: '', code: 'CNV_1511', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 208, name : 'CNV_1512', spec: '', code: 'CNV_1512', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 209, name : 'CNV_1520', spec: '', code: 'CNV_1520', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 210, name : 'CNV_1521', spec: '', code: 'CNV_1521', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 211, name : 'CNV_1522', spec: '', code: 'CNV_1522', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 287, name : 'CNV_2360', spec: '', code: 'CNV_2360', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 288, name : 'CNV_2361', spec: '', code: 'CNV_2361', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 289, name : 'CNV_2362', spec: '', code: 'CNV_2362', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 290, name : 'CNV_2363', spec: '', code: 'CNV_2363', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 291, name : 'CNV_2370', spec: '', code: 'CNV_2370', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 292, name : 'CNV_2371', spec: '', code: 'CNV_2371', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 293, name : 'CNV_2372', spec: '', code: 'CNV_2372', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 294, name : 'CNV_2373', spec: '', code: 'CNV_2373', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 295, name : 'CNV_2374', spec: '', code: 'CNV_2374', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 296, name : 'CNV_2375', spec: '', code: 'CNV_2375', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 297, name : 'CNV_2376', spec: '', code: 'CNV_2376', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 298, name : 'CNV_2380', spec: '', code: 'CNV_2380', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 299, name : 'CNV_2381', spec: '', code: 'CNV_2381', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 300, name : 'CNV_2382', spec: '', code: 'CNV_2382', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 301, name : 'CNV_2383', spec: '', code: 'CNV_2383', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 302, name : 'CNV_2400', spec: '', code: 'CNV_2400', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 303, name : 'CNV_2401', spec: '', code: 'CNV_2401', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 304, name : 'CNV_2402', spec: '', code: 'CNV_2402', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 305, name : 'CNV_2403', spec: '', code: 'CNV_2403', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 306, name : 'CNV_2405', spec: '', code: 'CNV_2405', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 307, name : 'CNV_2406', spec: '', code: 'CNV_2406', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 308, name : 'CNV_2407', spec: '', code: 'CNV_2407', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 309, name : 'CNV_2110', spec: '', code: 'CNV_2110', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 310, name : 'CNV_2111', spec: '', code: 'CNV_2111', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 311, name : 'CNV_2112', spec: '', code: 'CNV_2112', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 312, name : 'CNV_2120', spec: '', code: 'CNV_2120', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 313, name : 'CNV_2121', spec: '', code: 'CNV_2121', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 314, name : 'CNV_2122', spec: '', code: 'CNV_2122', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 315, name : 'CNV_2125', spec: '', code: 'CNV_2125', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 316, name : 'CNV_2126', spec: '', code: 'CNV_2126', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 317, name : 'CNV_2130', spec: '', code: 'CNV_2130', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 318, name : 'CNV_2131', spec: '', code: 'CNV_2131', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 319, name : 'CNV_2132', spec: '', code: 'CNV_2132', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 320, name : 'CNV_2135', spec: '', code: 'CNV_2135', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 321, name : 'CNV_2136', spec: '', code: 'CNV_2136', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 322, name : 'CNV_2140', spec: '', code: 'CNV_2140', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 323, name : 'CNV_2141', spec: '', code: 'CNV_2141', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 324, name : 'CNV_2142', spec: '', code: 'CNV_2142', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 325, name : 'CNV_2145', spec: '', code: 'CNV_2145', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 326, name : 'CNV_2146', spec: '', code: 'CNV_2146', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 327, name : 'CNV_2150', spec: '', code: 'CNV_2150', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 328, name : 'CNV_2151', spec: '', code: 'CNV_2151', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 329, name : 'CNV_2152', spec: '', code: 'CNV_2152', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 330, name : 'CNV_2155', spec: '', code: 'CNV_2155', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 331, name : 'CNV_2156', spec: '', code: 'CNV_2156', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 332, name : 'CNV_2160', spec: '', code: 'CNV_2160', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 333, name : 'CNV_2161', spec: '', code: 'CNV_2161', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 334, name : 'CNV_2162', spec: '', code: 'CNV_2162', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 335, name : 'CNV_2165', spec: '', code: 'CNV_2165', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 336, name : 'CNV_2166', spec: '', code: 'CNV_2166', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 337, name : 'CNV_2170', spec: '', code: 'CNV_2170', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 338, name : 'CNV_2171', spec: '', code: 'CNV_2171', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 339, name : 'CNV_2172', spec: '', code: 'CNV_2172', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 340, name : 'CNV_2175', spec: '', code: 'CNV_2175', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 341, name : 'CNV_2176', spec: '', code: 'CNV_2176', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 342, name : 'CNV_2180', spec: '', code: 'CNV_2180', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 343, name : 'CNV_2181', spec: '', code: 'CNV_2181', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 344, name : 'CNV_2182', spec: '', code: 'CNV_2182', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 345, name : 'CNV_2185', spec: '', code: 'CNV_2185', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 346, name : 'CNV_2186', spec: '', code: 'CNV_2186', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 347, name : 'CNV_2190', spec: '', code: 'CNV_2190', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 348, name : 'CNV_2191', spec: '', code: 'CNV_2191', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 349, name : 'CNV_2192', spec: '', code: 'CNV_2192', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 350, name : 'CNV_2195', spec: '', code: 'CNV_2195', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 351, name : 'CNV_2196', spec: '', code: 'CNV_2196', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 352, name : 'CNV_2200', spec: '', code: 'CNV_2200', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 353, name : 'CNV_2201', spec: '', code: 'CNV_2201', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 354, name : 'CNV_2202', spec: '', code: 'CNV_2202', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 355, name : 'CNV_2310', spec: '', code: 'CNV_2310', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 356, name : 'CNV_2311', spec: '', code: 'CNV_2311', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 357, name : 'CNV_2312', spec: '', code: 'CNV_2312', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 358, name : 'CNV_2313', spec: '', code: 'CNV_2313', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 359, name : 'CNV_2314', spec: '', code: 'CNV_2314', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 360, name : 'CNV_2315', spec: '', code: 'CNV_2315', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 361, name : 'CNV_2316', spec: '', code: 'CNV_2316', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 362, name : 'CNV_2320', spec: '', code: 'CNV_2320', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 363, name : 'CNV_2321', spec: '', code: 'CNV_2321', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 364, name : 'CNV_2322', spec: '', code: 'CNV_2322', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 365, name : 'CNV_2323', spec: '', code: 'CNV_2323', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 366, name : 'CNV_2330', spec: '', code: 'CNV_2330', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 367, name : 'CNV_2331', spec: '', code: 'CNV_2331', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 368, name : 'CNV_2332', spec: '', code: 'CNV_2332', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 369, name : 'CNV_2333', spec: '', code: 'CNV_2333', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 370, name : 'CNV_2334', spec: '', code: 'CNV_2334', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 371, name : 'CNV_2335', spec: '', code: 'CNV_2335', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 372, name : 'CNV_2336', spec: '', code: 'CNV_2336', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 373, name : 'CNV_2340', spec: '', code: 'CNV_2340', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 374, name : 'CNV_2341', spec: '', code: 'CNV_2341', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 375, name : 'CNV_2342', spec: '', code: 'CNV_2342', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 376, name : 'CNV_2343', spec: '', code: 'CNV_2343', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 377, name : 'CNV_2350', spec: '', code: 'CNV_2350', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 378, name : 'CNV_2351', spec: '', code: 'CNV_2351', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 379, name : 'CNV_2352', spec: '', code: 'CNV_2352', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 380, name : 'CNV_2353', spec: '', code: 'CNV_2353', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 381, name : 'CNV_2354', spec: '', code: 'CNV_2354', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 382, name : 'CNV_2355', spec: '', code: 'CNV_2355', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 383, name : 'CNV_2356', spec: '', code: 'CNV_2356', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 384, name : 'CNV_3117', spec: '', code: 'CNV_3117', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 385, name : 'CNV_3118', spec: '', code: 'CNV_3118', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 386, name : 'CNV_3119', spec: '', code: 'CNV_3119', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 387, name : 'CNV_3120', spec: '', code: 'CNV_3120', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 388, name : 'CNV_3121', spec: '', code: 'CNV_3121', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 389, name : 'CNV_3122', spec: '', code: 'CNV_3122', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 390, name : 'CNV_3123', spec: '', code: 'CNV_3123', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 391, name : 'CNV_3124', spec: '', code: 'CNV_3124', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 392, name : 'CNV_3125', spec: '', code: 'CNV_3125', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 393, name : 'CNV_3126', spec: '', code: 'CNV_3126', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 394, name : 'CNV_3127', spec: '', code: 'CNV_3127', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 395, name : 'CNV_3128', spec: '', code: 'CNV_3128', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 396, name : 'CNV_3129', spec: '', code: 'CNV_3129', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 397, name : 'CNV_3130', spec: '', code: 'CNV_3130', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 398, name : 'CNV_3131', spec: '', code: 'CNV_3131', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 399, name : 'CNV_3132', spec: '', code: 'CNV_3132', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 400, name : 'CNV_3133', spec: '', code: 'CNV_3133', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 401, name : 'CNV_3134', spec: '', code: 'CNV_3134', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 402, name : 'CNV_3135', spec: '', code: 'CNV_3135', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 403, name : 'CNV_3136', spec: '', code: 'CNV_3136', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 404, name : 'CNV_3137', spec: '', code: 'CNV_3137', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 405, name : 'CNV_3138', spec: '', code: 'CNV_3138', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 406, name : 'CNV_3139', spec: '', code: 'CNV_3139', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 407, name : 'CNV_3140', spec: '', code: 'CNV_3140', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 408, name : 'CNV_3141', spec: '', code: 'CNV_3141', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 409, name : 'CNV_3142', spec: '', code: 'CNV_3142', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 410, name : 'CNV_3143', spec: '', code: 'CNV_3143', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 411, name : 'CNV_3144', spec: '', code: 'CNV_3144', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 412, name : 'CNV_3150', spec: '', code: 'CNV_3150', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 413, name : 'CNV_3151', spec: '', code: 'CNV_3151', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 414, name : 'CNV_3152', spec: '', code: 'CNV_3152', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 415, name : 'CNV_3153', spec: '', code: 'CNV_3153', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 416, name : 'CNV_3154', spec: '', code: 'CNV_3154', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 417, name : 'CNV_3155', spec: '', code: 'CNV_3155', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 418, name : 'CNV_3160', spec: '', code: 'CNV_3160', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 419, name : 'CNV_3161', spec: '', code: 'CNV_3161', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 420, name : 'CNV_3162', spec: '', code: 'CNV_3162', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 421, name : 'CNV_3163', spec: '', code: 'CNV_3163', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 422, name : 'CNV_3164', spec: '', code: 'CNV_3164', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 423, name : 'CNV_3165', spec: '', code: 'CNV_3165', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 424, name : 'CNV_3166', spec: '', code: 'CNV_3166', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 425, name : 'CNV_3170', spec: '', code: 'CNV_3170', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 426, name : 'CNV_3171', spec: '', code: 'CNV_3171', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 427, name : 'CNV_3172', spec: '', code: 'CNV_3172', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 428, name : 'CNV_3173', spec: '', code: 'CNV_3173', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 429, name : 'CNV_3174', spec: '', code: 'CNV_3174', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 430, name : 'CNV_3175', spec: '', code: 'CNV_3175', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 431, name : 'CNV_3176', spec: '', code: 'CNV_3176', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 432, name : 'CNV_3177', spec: '', code: 'CNV_3177', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 433, name : 'CNV_3178', spec: '', code: 'CNV_3178', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 434, name : 'CNV_3180', spec: '', code: 'CNV_3180', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 435, name : 'CNV_3181', spec: '', code: 'CNV_3181', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 436, name : 'CNV_3182', spec: '', code: 'CNV_3182', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 437, name : 'CNV_3183', spec: '', code: 'CNV_3183', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 438, name : 'CNV_3184', spec: '', code: 'CNV_3184', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 439, name : 'CNV_3185', spec: '', code: 'CNV_3185', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 440, name : 'CNV_3186', spec: '', code: 'CNV_3186', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 441, name : 'CNV_3190', spec: '', code: 'CNV_3190', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 442, name : 'CNV_3191', spec: '', code: 'CNV_3191', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 443, name : 'CNV_3192', spec: '', code: 'CNV_3192', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 444, name : 'CNV_3193', spec: '', code: 'CNV_3193', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 445, name : 'CNV_3194', spec: '', code: 'CNV_3194', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 446, name : 'CNV_3195', spec: '', code: 'CNV_3195', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 447, name : 'CNV_3196', spec: '', code: 'CNV_3196', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 448, name : 'CNV_3197', spec: '', code: 'CNV_3197', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 449, name : 'CNV_3198', spec: '', code: 'CNV_3198', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 450, name : 'CNV_3199', spec: '', code: 'CNV_3199', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 451, name : 'CNV_3217', spec: '', code: 'CNV_3217', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 452, name : 'CNV_3218', spec: '', code: 'CNV_3218', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 453, name : 'CNV_3219', spec: '', code: 'CNV_3219', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 454, name : 'CNV_3220', spec: '', code: 'CNV_3220', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 455, name : 'CNV_3221', spec: '', code: 'CNV_3221', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 456, name : 'CNV_3222', spec: '', code: 'CNV_3222', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 457, name : 'CNV_3223', spec: '', code: 'CNV_3223', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 458, name : 'CNV_3224', spec: '', code: 'CNV_3224', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 459, name : 'CNV_3225', spec: '', code: 'CNV_3225', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 460, name : 'CNV_3226', spec: '', code: 'CNV_3226', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 461, name : 'CNV_3227', spec: '', code: 'CNV_3227', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 462, name : 'CNV_3228', spec: '', code: 'CNV_3228', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 463, name : 'CNV_3229', spec: '', code: 'CNV_3229', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 464, name : 'CNV_3230', spec: '', code: 'CNV_3230', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 465, name : 'CNV_3231', spec: '', code: 'CNV_3231', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 466, name : 'CNV_3232', spec: '', code: 'CNV_3232', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 467, name : 'CNV_3233', spec: '', code: 'CNV_3233', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 468, name : 'CNV_3234', spec: '', code: 'CNV_3234', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 469, name : 'CNV_3235', spec: '', code: 'CNV_3235', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 470, name : 'CNV_3236', spec: '', code: 'CNV_3236', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 471, name : 'CNV_3240', spec: '', code: 'CNV_3240', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 472, name : 'CNV_3241', spec: '', code: 'CNV_3241', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 473, name : 'CNV_3242', spec: '', code: 'CNV_3242', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 474, name : 'CNV_3243', spec: '', code: 'CNV_3243', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 475, name : 'CNV_3244', spec: '', code: 'CNV_3244', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 476, name : 'CNV_3245', spec: '', code: 'CNV_3245', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 477, name : 'CNV_3246', spec: '', code: 'CNV_3246', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 478, name : 'CNV_3247', spec: '', code: 'CNV_3247', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 479, name : 'CNV_3250', spec: '', code: 'CNV_3250', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 480, name : 'CNV_3251', spec: '', code: 'CNV_3251', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 481, name : 'CNV_3252', spec: '', code: 'CNV_3252', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 482, name : 'CNV_3253', spec: '', code: 'CNV_3253', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 483, name : 'CNV_3254', spec: '', code: 'CNV_3254', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 484, name : 'CNV_3255', spec: '', code: 'CNV_3255', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 485, name : 'CNV_3260', spec: '', code: 'CNV_3260', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 486, name : 'CNV_3261', spec: '', code: 'CNV_3261', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 487, name : 'CNV_3262', spec: '', code: 'CNV_3262', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 488, name : 'CNV_3263', spec: '', code: 'CNV_3263', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 489, name : 'CNV_3264', spec: '', code: 'CNV_3264', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 490, name : 'CNV_3265', spec: '', code: 'CNV_3265', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 491, name : 'CNV_3266', spec: '', code: 'CNV_3266', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 492, name : 'CNV_3270', spec: '', code: 'CNV_3270', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 493, name : 'CNV_3271', spec: '', code: 'CNV_3271', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 494, name : 'CNV_3272', spec: '', code: 'CNV_3272', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 495, name : 'CNV_3273', spec: '', code: 'CNV_3273', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 496, name : 'CNV_3274', spec: '', code: 'CNV_3274', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 497, name : 'CNV_3275', spec: '', code: 'CNV_3275', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 498, name : 'CNV_3276', spec: '', code: 'CNV_3276', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 499, name : 'CNV_3277', spec: '', code: 'CNV_3277', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 500, name : 'CNV_3278', spec: '', code: 'CNV_3278', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 501, name : 'CNV_3280', spec: '', code: 'CNV_3280', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 502, name : 'CNV_3281', spec: '', code: 'CNV_3281', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 503, name : 'CNV_3282', spec: '', code: 'CNV_3282', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 504, name : 'CNV_3283', spec: '', code: 'CNV_3283', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 505, name : 'CNV_3284', spec: '', code: 'CNV_3284', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 506, name : 'CNV_3285', spec: '', code: 'CNV_3285', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 507, name : 'CNV_3286', spec: '', code: 'CNV_3286', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 508, name : 'CNV_3290', spec: '', code: 'CNV_3290', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 509, name : 'CNV_3291', spec: '', code: 'CNV_3291', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 510, name : 'CNV_3301', spec: '', code: 'CNV_3301', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 511, name : 'CNV_3302', spec: '', code: 'CNV_3302', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 512, name : 'CNV_3303', spec: '', code: 'CNV_3303', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 513, name : 'CNV_3304', spec: '', code: 'CNV_3304', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 514, name : 'CNV_3305', spec: '', code: 'CNV_3305', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 515, name : 'CNV_3306', spec: '', code: 'CNV_3306', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 516, name : 'CNV_3307', spec: '', code: 'CNV_3307', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 517, name : 'CNV_3310', spec: '', code: 'CNV_3310', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 518, name : 'CNV_3311', spec: '', code: 'CNV_3311', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 519, name : 'CNV_3312', spec: '', code: 'CNV_3312', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 520, name : 'CNV_3313', spec: '', code: 'CNV_3313', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 521, name : 'CNV_3314', spec: '', code: 'CNV_3314', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 522, name : 'CNV_3315', spec: '', code: 'CNV_3315', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 523, name : 'CNV_3316', spec: '', code: 'CNV_3316', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 524, name : 'CNV_3317', spec: '', code: 'CNV_3317', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 525, name : 'CNV_3318', spec: '', code: 'CNV_3318', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 526, name : 'CNV_3320', spec: '', code: 'CNV_3320', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 527, name : 'CNV_3321', spec: '', code: 'CNV_3321', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 528, name : 'CNV_3322', spec: '', code: 'CNV_3322', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 529, name : 'CNV_3323', spec: '', code: 'CNV_3323', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 530, name : 'CNV_3330', spec: '', code: 'CNV_3330', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 531, name : 'CNV_3331', spec: '', code: 'CNV_3331', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 532, name : 'CNV_3332', spec: '', code: 'CNV_3332', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 533, name : 'CNV_3333', spec: '', code: 'CNV_3333', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 534, name : 'CNV_3334', spec: '', code: 'CNV_3334', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 535, name : 'CNV_3335', spec: '', code: 'CNV_3335', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 536, name : 'CNV_3336', spec: '', code: 'CNV_3336', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 537, name : 'CNV_3510', spec: '', code: 'CNV_3510', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 538, name : 'CNV_3511', spec: '', code: 'CNV_3511', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 539, name : 'CNV_3512', spec: '', code: 'CNV_3512', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 540, name : 'CNV_3513', spec: '', code: 'CNV_3513', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 541, name : 'CNV_3514', spec: '', code: 'CNV_3514', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 542, name : 'CNV_3515', spec: '', code: 'CNV_3515', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 543, name : 'CNV_3520', spec: '', code: 'CNV_3520', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 544, name : 'CNV_3521', spec: '', code: 'CNV_3521', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 545, name : 'CNV_3522', spec: '', code: 'CNV_3522', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 546, name : 'CNV_3523', spec: '', code: 'CNV_3523', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 547, name : 'CNV_3524', spec: '', code: 'CNV_3524', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 548, name : 'CNV_3525', spec: '', code: 'CNV_3525', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 549, name : 'CNV_3530', spec: '', code: 'CNV_3530', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 550, name : 'CNV_3531', spec: '', code: 'CNV_3531', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 551, name : 'CNV_3532', spec: '', code: 'CNV_3532', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 552, name : 'CNV_3533', spec: '', code: 'CNV_3533', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 553, name : 'CNV_3534', spec: '', code: 'CNV_3534', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 554, name : 'CNV_3535', spec: '', code: 'CNV_3535', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 555, name : 'CNV_3540', spec: '', code: 'CNV_3540', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 556, name : 'CNV_3541', spec: '', code: 'CNV_3541', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 557, name : 'CNV_3542', spec: '', code: 'CNV_3542', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 558, name : 'CNV_3543', spec: '', code: 'CNV_3543', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 559, name : 'CNV_3544', spec: '', code: 'CNV_3544', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 560, name : 'CNV_3545', spec: '', code: 'CNV_3545', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 561, name : 'CNV_3550', spec: '', code: 'CNV_3550', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 562, name : 'CNV_3551', spec: '', code: 'CNV_3551', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 563, name : 'CNV_3552', spec: '', code: 'CNV_3552', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 564, name : 'CNV_3553', spec: '', code: 'CNV_3553', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 565, name : 'CNV_3554', spec: '', code: 'CNV_3554', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 566, name : 'CNV_3555', spec: '', code: 'CNV_3555', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 567, name : 'CNV_3560', spec: '', code: 'CNV_3560', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 568, name : 'CNV_3561', spec: '', code: 'CNV_3561', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 569, name : 'CNV_3562', spec: '', code: 'CNV_3562', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 570, name : 'CNV_3563', spec: '', code: 'CNV_3563', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 571, name : 'CNV_3564', spec: '', code: 'CNV_3564', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 572, name : 'CNV_3565', spec: '', code: 'CNV_3565', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 573, name : 'CNV_3570', spec: '', code: 'CNV_3570', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 574, name : 'CNV_3571', spec: '', code: 'CNV_3571', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 575, name : 'CNV_3572', spec: '', code: 'CNV_3572', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 576, name : 'CNV_3573', spec: '', code: 'CNV_3573', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 577, name : 'CNV_3574', spec: '', code: 'CNV_3574', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 578, name : 'CNV_3575', spec: '', code: 'CNV_3575', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 579, name : 'CNV_3580', spec: '', code: 'CNV_3580', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 580, name : 'CNV_3581', spec: '', code: 'CNV_3581', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 581, name : 'CNV_3582', spec: '', code: 'CNV_3582', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 582, name : 'CNV_3583', spec: '', code: 'CNV_3583', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 583, name : 'CNV_3584', spec: '', code: 'CNV_3584', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 584, name : 'CNV_3585', spec: '', code: 'CNV_3585', equipment_type: {id : equipmentTypeList[0].id}, warehouse: {id : 6} },
      { id : 585, name : 'RGV_1_1', spec: '', code: 'RGV_1_1', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 586, name : 'RGV_1_2', spec: '', code: 'RGV_1_2', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 587, name : 'RGV_1_3', spec: '', code: 'RGV_1_3', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 588, name : 'RGV_1_4', spec: '', code: 'RGV_1_4', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 589, name : 'RGV_1_5', spec: '', code: 'RGV_1_5', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 590, name : 'RGV_1_6', spec: '', code: 'RGV_1_6', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 591, name : 'RGV_1_7', spec: '', code: 'RGV_1_7', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 592, name : 'RGV_1_8', spec: '', code: 'RGV_1_8', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 593, name : 'RGV_1_9', spec: '', code: 'RGV_1_9', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 594, name : 'RGV_1_10', spec: '', code: 'RGV_1_10', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 595, name : 'RGV_1_11', spec: '', code: 'RGV_1_11', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 596, name : 'RGV_1_12', spec: '', code: 'RGV_1_12', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 597, name : 'RGV_2_1', spec: '', code: 'RGV_2_1', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 598, name : 'RGV_2_2', spec: '', code: 'RGV_2_2', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 599, name : 'RGV_2_3', spec: '', code: 'RGV_2_3', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 600, name : 'RGV_2_4', spec: '', code: 'RGV_2_4', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 601, name : 'RGV_2_5', spec: '', code: 'RGV_2_5', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 602, name : 'RGV_2_6', spec: '', code: 'RGV_2_6', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 603, name : 'RGV_2_7', spec: '', code: 'RGV_2_7', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 604, name : 'RGV_2_8', spec: '', code: 'RGV_2_8', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 605, name : 'RGV_2_9', spec: '', code: 'RGV_2_9', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 606, name : 'RGV_2_10', spec: '', code: 'RGV_2_10', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 607, name : 'RGV_2_11', spec: '', code: 'RGV_2_11', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
      { id : 608, name : 'RGV_2_12', spec: '', code: 'RGV_2_12', equipment_type: {id : equipmentTypeList[1].id}, warehouse: {id : 6} },
    ];

    await this.equipmentRepository.save(equipmentDefaultList);
    this.logger.log('data inserted!');
  }

  async insertTestData(): Promise<void> {
    this.logger.log('No equipment found, inserting debug data...');


    this.logger.log('Debug data inserted!');
  }
  
}
